services:
  postgres:
    image: 'postgres:latest'
    environment:
    - 'POSTGRES_DB=mydatabase'
    - 'POSTGRES_PASSWORD=secret'
    - 'POSTGRES_USER=myuser'
    ports:
    - '5432:5432'

  dashboard:
    image: "ghcr.io/making/spring-batch-dashboard:jvm"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase"
      - "SPRING_DATASOURCE_USERNAME=myuser"
      - "SPRING_DATASOURCE_PASSWORD=secret"
      - "SPRING_SECURITY_USER_NAME=admin"
      - "SPRING_SECURITY_USER_PASSWORD=secret"
    ports:
      - "8080:8080"
